/**
 * Real construction footage (supplied, unedited apart from transcoding).
 * Derivatives generated by tools/scripts/build_assets.py from source-assets/.
 */
export type FootageClip = {
  id: string;
  phase: string;
  title: string;
  caption: string;
  src: string;
  poster: string;
};

const clip = (id: string, phase: string, title: string, caption: string): FootageClip => ({
  id,
  phase,
  title,
  caption,
  src: `/videos/${id}.mp4`,
  poster: `/videos/${id}.jpg`,
});

export const footage: FootageClip[] = [
  clip("stonework-foundation", "Foundation", "Stone by stone", "Retaining walls laid by hand — the ground work every building stands on."),
  clip("steel-columns", "Structure", "The frame goes up", "Steel columns and decking arriving on site."),
  clip("steel-roof", "Structure", "Under the steel", "Looking up through the roof framing and decking."),
  clip("scaffold-arches", "Masonry", "Arches in progress", "Brick arches rising within the scaffold."),
  clip("scaffold-crew", "Masonry", "Many hands", "Crews working level by level across the facade."),
  clip("brick-arches", "Masonry", "Brick & shade", "Exposed brickwork and arch detailing, framed by existing trees."),
  clip("facade-rise", "Facade", "Toward the facade", "From stone base to finished upper floors."),
  clip("site-team", "On site", "On site, together", "Reviewing work and details directly on site."),
];

export const heroFootage = footage[0];
